project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - labs.qmd
      - resources.qmd
      - href: ./E155-Project/project.qmd
        text: Project
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



